name: acme-oidc
on: workflow_dispatch

permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
jobs:
  ga-jfrog-get-token:
    runs-on: ubuntu-latest

    steps:
      # Use the specific setup-cli branch
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_URL: https://soleng.jfrog.io
        with:
          oidc-provider-name: carlosmm-github-integration
          oidc-audience: carlosmm-github

      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Run a jfrog command
        # Run a jfrog command to trigger the token exchnage
        run: |
          jf rt curl /api/repositories